version: "3.9"
services:
  api:
    build: { context: ., dockerfile: infra/Dockerfile.api }
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
    volumes:
      - ./api:/app/api
      - ./services:/app/services
      - ./db:/app/db
      - ./storage:/app/storage
      - ./workers:/app/workers
    depends_on: [db, redis]
    ports: ["8000:8000"]
    command: bash -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports: ["3000:3000"]
    environment:
      VITE_API_BASE_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:8000
      VITE_AUTH_ENABLED: "true"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on: [api]

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD-SHELL","redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata: {}

