version: "3.9"
services:
  api:
    build: { context: .., dockerfile: infra/Dockerfile.api }
    env_file: ../env.example
    depends_on: [db, redis]
    ports: ["8000:8000"]
    volumes: ["..:/app"]
  worker:
    build: { context: .., dockerfile: infra/Dockerfile.worker }
    env_file: ../env.example
    depends_on: [db, redis]
    volumes: ["..:/app"]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes: ["minio:/data"]
volumes:
  pgdata: {}
  minio: {}
