global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI API
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Celery Workers: expose a /metrics endpoint to enable this job
  # - job_name: 'workers'
  #   static_configs:
  #     - targets: ['worker:8001']
  #   metrics_path: '/metrics'
  #   scrape_interval: 10s
  #   scrape_timeout: 5s

  # Redis and Postgres exporters are not configured by default.
  # Enable when exporters are added:
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']
  #   scrape_interval: 30s
  #   scrape_timeout: 10s
  #
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']
  #   scrape_interval: 30s
  #   scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - grafana:3000
