name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
      redis:
        image: redis:7
        ports: ["6379:6379"]
      minio:
        image: minio/minio
        ports: ["9000:9000","9001:9001"]
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/ready || exit 1"
          --health-interval 5s --health-timeout 5s --health-retries 20
          --command "server /data --console-address :9001"
    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/postgres
      REDIS_URL: redis://localhost:6379/0
      S3_ENDPOINT: http://localhost:9000
      S3_REGION: us-east-1
      S3_BUCKET: promoai
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -U pip uv
      - run: uv pip install --system -r requirements.txt || true
      - run: pip install -e . || true
      - run: pre-commit install
      - run: bash scripts/banlist.sh
      - run: bash scripts/check_wireup.sh
      - run: python -c "import boto3, fitz; print('deps ok')"
      - run: python -m alembic upgrade head
      - name: Start API
        run: python -m uvicorn api.main:app --host 0.0.0.0 --port 8000 &
      - name: Start Celery Worker
        run: python -m celery -A workers.app worker -Q parse,chunk,index --concurrency 1 &
      - name: Wait for services
        run: sleep 5
      - name: Check API health
        run: curl -f http://localhost:8000/healthz || exit 1
      - name: Run tests
        run: pytest -q tests/test_retrieve.py tests/test_query_api.py tests/test_context_builder.py --maxfail=1
